package com.example.demo.enums;

public enum AdminActionHistoryCategory {

    TEST,
    ACCESS_ADMIN_MAIN,
    ACCESS_ADMIN_CREATE_FORM,
    // 검색 페이지 접근
    SEARCH_ADMIN,
    SEARCH_EXPERT,
    SEARCH_MANAGER,
    SEARCH_MEMBER,
    SEARCH_USERS_DELETED,
    SEARCH_EXPERT_UNAPPROVE,
    SEARCH_MANAGER_UNAPPROVE,

    // 리스트 페이지 접근
    ACCESS_ADMIN_LIST,
    ACCESS_EXPERT_LIST,
    ACCESS_MANAGER_LIST,
    ACCESS_MEMBER_LIST,
    ACCESS_USERS_DELETED_LIST,
    ACCESS_EXPERT_UNAPPROVE_LIST,
    ACCESS_MANAGER_UNAPPROVE_LIST,
    ACCESS_MANAGER_CHILD_LIST,
    ACCESS_MEMBER_CHILD_LIST,

    // 상세 페이지 접근
    ACCESS_EXPERT_UPDATE_FORM,
    ACCESS_MANAGER_UPDATE_FORM,
    ACCESS_MEMBER_UPDATE_FORM,
    ACCESS_ADMIN_UPDATE_FORM,
    ACCESS_USERS_DELETED_RESTORE_FORM,

    // [담당자, 전문가] 승인
    APPROVE_EXPERT,
    APPROVE_MANAGER,

    // 복구 하기
    RESTORE_USERS,

    // 수정 하기
    UPDATE_EXPERT,
    UPDATE_MANAGER,
    UPDATE_MEMBER,
    CHECK_VALIDATION_UPDATE_EXPERT,
    CHECK_VALIDATION_UPDATE_MANAGER,
    CHECK_VALIDATION_UPDATE_MEMBER,
    // 관리자 생성
    CREATE_ADMIN,
    CHECK_ADMIN_VALIDATION,
    INITIALIZE_ADMIN_PASSWORD,

}
